name: On Semantic Release (build & publish image)
on:
  release:
    types: [ released ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./build/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/aam-digital/ndb-admin:${{ github.event.release.tag_name }},ghcr.io/aam-digital/ndb-admin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
